version: '3.8'
services:
  postgres:
    container_name: postgres_news
    image: postgres:15
    ports:
      - "5433:5432"
    volumes: 
      - db:/var/lib/postgres/data 
    restart: always
    env_file:
      - .env
volumes:
  db:
  redis:
