version: '3.8'

services:
  postgres:
    container_name: postgresnews
    image: postgres:15
    ports:
      - "5433:5432"
    volumes: 
      - db:/var/lib/postgres/data 
    restart: always
    env_file:
      - .env
  pgadmin: 
    image: dpage/pgadmin4
    container_name: pgadminnews
    depends_on:
      - postgres
    ports:
      - "5555:80"
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    logging:
      driver: none
    restart: unless-stopped
volumes:
  db:
  pgadmin-data:
